apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eventflow
resources:
  - namespace.yaml
  - configmap.yaml
  - api-gateway.yaml
  - consumer-worker.yaml
  - workflow-engine.yaml
