global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: workflow-engine
    static_configs:
      - targets: ["workflow-engine:8081"]

  - job_name: consumer-worker
    static_configs:
      - targets: ["consumer-worker:8082"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka:9101"]
